AssetManagementApp/Models/DnsRecord.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AssetManagementApp.Models
{
    public class DnsRecord
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Content { get; set; }
    }
}

AssetManagementApp/Models/DomainList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations.Schema;

namespace AssetManagementApp.Models
{
    public class DomainList
    {
        
        public string Domain { get; set; }
    }
}

AssetManagementApp/Models/ErrorViewModel.cs
using System;

namespace AssetManagementApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AssetManagementApp/Models/HomeViewModel.cs
// <copyright file="HomeViewModel.cs" company="Nestlé">
// Copyright (c) Nestlé. All rights reserved.
// </copyright>

namespace Nestle.amaMvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;


    /// <summary>
    /// Represents view model for home controller
    /// </summary>
    public class HomeViewModel
    {
        /// <summary>
        /// Gets or sets the list of annoucements
        /// </summary>


        /// <summary>
        /// Gets or sets the summary of project count
        /// </summary>

    }
}

AssetManagementApp/Controllers/DnsRecordsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AssetManagementApp.Models;
using System.Data;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;

namespace AssetManagementApp.Controllers
{
    public class DnsRecordsController : Controller
    {
        private readonly DnsRecordDbContext _context;

        public DnsRecordsController(DnsRecordDbContext context)
        {
            _context = context;
        }

        // GET: DnsRecords
        public async Task<IActionResult> Index()
        {
            return View(await _context.DnsRecord.ToListAsync());
        }

        // GET: DnsRecords/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dnsRecord = await _context.DnsRecord
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dnsRecord == null)
            {
                return NotFound();
            }

            return View(dnsRecord);
        }


        // GET: DnsRecords/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DnsRecords/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Type,Content")] DnsRecord dnsRecord)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dnsRecord);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dnsRecord);
        }

        // GET: DnsRecords/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dnsRecord = await _context.DnsRecord.FindAsync(id);
            if (dnsRecord == null)
            {
                return NotFound();
            }
            return View(dnsRecord);
        }

        // POST: DnsRecords/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Type,Content")] DnsRecord dnsRecord)
        {
            if (id != dnsRecord.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dnsRecord);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DnsRecordExists(dnsRecord.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dnsRecord);
        }

        // GET: DnsRecords/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dnsRecord = await _context.DnsRecord
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dnsRecord == null)
            {
                return NotFound();
            }

            return View(dnsRecord);
        }

        // POST: DnsRecords/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dnsRecord = await _context.DnsRecord.FindAsync(id);
            _context.DnsRecord.Remove(dnsRecord);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DnsRecordExists(int id)
        {
            return _context.DnsRecord.Any(e => e.Id == id);
        }
    }
}

AssetManagementApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AssetManagementApp.Models;

namespace AssetManagementApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AssetManagementApp/Views/DnsRecords/Create.cshtml
@model AssetManagementApp.Models.DnsRecord

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>DnsRecord</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AssetManagementApp/Views/DnsRecords/Delete.cshtml
@model AssetManagementApp.Models.DnsRecord

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DnsRecord</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AssetManagementApp/Views/DnsRecords/Details.cshtml
@model AssetManagementApp.Models.DnsRecord

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>DnsRecord</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AssetManagementApp/Views/DnsRecords/Edit.cshtml
@model AssetManagementApp.Models.DnsRecord

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>DnsRecord</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AssetManagementApp/Views/DnsRecords/Import.cshtml
@model AssetManagementApp.Models.DomainList
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using System.Data;

@{
    ViewData["Title"] = "Import";
}

<h2>Import</h2>

<h4>DnsRecord</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="DnsRecords" asp-action="Import" method="post" enctype="multipart/form-data">
            <input type="file" name="postedFile" />
            <input type="submit" value="Import" />
        </form>
        @if (Model != null)
    {
        <hr />
       
    }
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AssetManagementApp/Views/DnsRecords/Index.cshtml
@model IEnumerable<AssetManagementApp.Models.DnsRecord>

@{
    ViewData["Title"] = "DNS-Records";
}

<h2>Domain List</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Content)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Content)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

AssetManagementApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
   
</div>

<div class="row">
   
</div>

AssetManagementApp/Views/Shared/_Layout.cshtml
@using System.Configuration

@{
    @*var env = ConfigurationManager.AppSettings["Environment"];
    string envTitle;
    switch (env)
    {
        case "PROD":
            envTitle = string.Empty;
            break;

        case "TEST":
            envTitle = "Testsystem";
            break;

        case "DEV":
        default:
            envTitle = "Entwicklungssystem";
            break;
    }*@
    Random rdn = new Random();

    var pageVersion = rdn.Next();

}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AssetManagementApp</title>



    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/main.css" />
        <link rel="stylesheet" href="~/css/*.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div id="header" class="page-navbar">
        <!-- .navbar-brand -->
        <a href="@Url.Action("Index", "Home")" class="navbar-brand hidden-xs hidden-sm">
            <img src="@Url.Content("~/images/logo.png")" class="logo hidden-xs" alt="Nestlé DTS - AssetManagementApp">
            <img src="@Url.Content("~/images/logosm.png")" class="logo-sm hidden-lg hidden-md" alt="Nestlé DTS - AssetManagementApp">
        </a>
        <!-- / navbar-brand -->
        <!-- .no-collapse -->
        <div id="navbar-no-collapse" class="navbar-no-collapse">
            <!-- top left nav -->
            <ul class="nav navbar-nav">
                <li class="toggle-sidebar">
                    <a href="#">
                        <i class="fa fa-reorder"></i>
                        <span class="sr-only">Collapse sidebar</span>
                    </a>
                </li>
                <li style="padding-top: 8px;">
                    <h4 id="PageTitle">@ViewBag.Title</h4>
                </li>
            </ul>
            <!-- / top left nav -->
            <!-- top right nav -->
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <div style="color: red; margin-top: 15px; margin-right: 30px;">Staging</div>

                </li>
            </ul>
            <!-- / top right nav -->
        </div>
        <!-- / collapse -->
    </div>
    <!-- / page-navbar -->
    <!-- #wrapper -->
    <div id="wrapper">
        <!-- .page-sidebar -->
        <aside id="sidebar" class="page-sidebar hidden-md hidden-sm hidden-xs">
            <!-- Start .sidebar-inner -->
            <div class="sidebar-inner">
                <!-- Start .sidebar-scrollarea -->
                <div class="sidebar-scrollarea">
                    <!--  .sidebar-panel -->
                    <div class="sidebar-panel">
                        <h5 class="sidebar-panel-title">Willkommen</h5>
                    </div>
                    <!-- / .sidebar-panel -->
                    <div class="user-info clearfix">
                        <img src="@Url.Content("~/images/employees/minion.jpg")" alt="avatar">
                        <span class="name">@User.Identity.Name </span>
                        <div class="btn-group">
                        </div>
                    </div>
                    <!--  .sidebar-panel -->
                    <div class="sidebar-panel">
                        <h5 class="sidebar-panel-title">Menü</h5>
                    </div>
                    <!-- / .sidebar-panel -->
                    <!-- .side-nav -->
                    <div class="side-nav">
                        <ul class="nav">
                            <li>
                                <a href="@Url.Action("Index", "Home")"><span class="txt">Home</span></a>
                                <a href="@Url.Action("Index", "DnsRecords")"><span class="txt">DNS-Checkup</span></a>
                            </li>
                            @*@if (Session.CanReview())
                            {
                                <li>
                                    <a href="@Url.Action("Index", "Review")"><i class="l-arrows-square-check"></i><span class="txt">Monatsreview</span></a>
                                </li>
                            }
                            <li>
                                <a href="@Url.Action("Index", "WorkItem")"><i class="l-basic-webpage"></i><span class="txt">Zeiterfassung</span></a>
                            </li>
                            <li class="hide">
                                <a href="@Url.Action("Absence", "Planner")"><i class="l-basic-webpage"></i><span class="txt">Abwesenheitsplanung</span></a>
                            </li>

                            <li>
                                <a href="@Url.Action("Index", "Project")"><i class="l-ecommerce-graph1"></i> <span class="txt">Projekte</span></a>
                                <ul class="sub">
                                    <li>
                                        <a href="@Url.Action("Index", "Project")"><span class="txt">Übersicht</span></a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Mine", "Project")"><span class="txt">Meine</span></a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Favorites", "Project")"><span class="txt">Favoriten</span></a>
                                    </li>
                                </ul>
                            </li> *@

                            @*
                            @if (Session.IsAdmin())
                            {
                                <li>
                                    <a href="#"><i class="l-software-layers2"></i><span class="txt">Administration</span></a>
                                    <ul class="sub">
                                        <li>
                                            <a href="@Url.Action("Index", "Employee")"><span class="txt">Mitarbeiter</span></a>
                                        </li>
                                        <li>
                                            <a href="@Url.Action("Index", "BusinessArea")"><span class="txt">Operativen</span></a>
                                        </li>
                                        <li>
                                            <a href="@Url.Action("Index", "DefaultHourRate")"><span class="txt">Stundens&auml;tze</span></a>
                                        </li>
                                        <li>
                                            <a href="@Url.Action("Manage", "Review")"><span class="txt">Monatsreview</span></a>
                                        </li>
                                        <li>
                                            <a href="@Url.Action("Manage", "Announcement")"><span class="txt">iTAB News</span></a>
                                        </li>
                                        <li>
                                            <a href="@Url.Action("FieldEditor", "Administration")"><span class="txt">Field Editor</span></a>
                                        </li>

                                    </ul>
                                </li>

                                <li>
                                    <a href="#"><i class="l-basic-mail"></i> <span class="txt">Berichte</span></a>
                                    <ul class="sub">
                                        <li>
                                            <a href="@Url.Action("Index", "Report", new { name = "EmployeeVacation" })"><span class="txt">Abwesenheitsbericht</span></a>
                                        </li>
                                        <li>
                                            <a href="@Url.Action("Index", "Report", new { name = "ExternalMaintenance" })"><span class="txt">Maintenance Externe</span></a>
                                        </li>
                                        <li>
                                            <a href="@Url.Action("Index", "Report", new { name = "BusinessAreaMaintenance" })"><span class="txt">Operativenverbrauch</span></a>
                                        </li>
                                        <li>
                                            <a href="@Url.Action("Index", "Report", new { name = "EmployeeExpenditure" })"><span class="txt">Mitarbeiterbetr&auml;ge</span></a>
                                        </li>
                                        <li>
                                            <a href="@Url.Action("Index", "Report", new { name = "Invoicing" })"><span class="txt">Rechnungsbetr&auml;ge</span></a>
                                        </li>
                                        <li>
                                            <a href="@Url.Action("Index", "Report", new { name = "Capacity" })"><span class="txt">Auslastung Projekte</span></a>
                                        </li>
                                        <li>
                                            <a href="@Url.Action("Index", "Report", new { name = "ProjectBudgetDifference" })"><span class="txt">Projekt-&Uuml;berhang</span></a>
                                        </li>
                                        <li>
                                            <a href="@Url.Action("Index", "Report", new { name = "ProjectBudget" })"><span class="txt">Projekt-Aufw&auml;nde Operativen</span></a>
                                        </li>
                                    </ul>
                                </li>
                            } *@

                        </ul>
                    </div>
                </div>
                <!-- End .sidebar-scrollarea -->

            </div>
            <!-- End .sidebar-inner -->
        </aside>

        <!-- End #right-sidebar -->
        <!-- .page-content -->
        <div class="page-content sidebar-page clearfix">
            <!-- .page-content-wrapper -->
            <div class="page-content-wrapper">
                <div class="page-content-inner">
                    <!-- Start .page-content-inner -->
                    <div id="page-header" class="clearfix hide">
                        <div class="page-header">
                            <h2>@ViewBag.Title</h2>
                        </div>
                    </div>
                    <!-- Start .row -->
                    <div class="row" style="margin-right: 2px;">
                        @RenderBody()
                    </div>
                    <!-- End .row -->
                </div>
                <!-- End .page-content-inner -->
            </div>
            <!-- / page-content-wrapper -->
        </div>
        <!-- / page-content -->
    </div>
    <!-- / #wrapper -->
    <!-- End #footer  -->
    <!-- Back to top -->
    <div id="back-to-top">
        <a href="#">Back to Top</a>
    </div>

    @*<partial name="_CookieConsentPartial" />*@

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2022 - AssetManagementApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>